### ISSUE TITLE
Can only connect from Electrum Wallet via hostname, not ip address (internal nor external)

### ISSUE THREAD

**Issue by maltokyo** [kyuupichan/electrumx#919]
My setup is as follows:

Ubuntu Server 18.04 - hostname: `myhost` and IP `192.168.1.3`  with fully synched full node and ElectrumX hosted (and the router has public IP  - let's say with public IP`1.2.3.4` with port forwarding for 50002 "on", and pointing to 192.168.1.3 )

Mac with Electrum wallet - IP `192.168.1.4` (same network as above, same router)

From my mac, I can connect to from Electrum wallet and use it perfecting using server as `myhost:50002` but CANNOT connect with `192.168.1.3:50002` or `1.2.3.4:50002`

Is there something I miss or some way to diagnose the issue?  From home network, all is ok as I can just use the hostname that works, but I cannot connect from same network with IP or from external network with public IP.  Please advise how I could troubleshoot this, I cant find any connection error in the logs of ElectrumX.

Docker file:
```
version: "3"

services:
  electrumx:
    image: lukechilds/electrumx
    ports:
      - "50002:50002"
    volumes:
      - /some/drive/zElectrumX_data:/data
    environment:
      - DAEMON_URL=un:pw:43782
      - COIN=BitcoinSegwit
```

Raised also here, in the docker repo: https://github.com/lukechilds/docker-electrumx/issues/42
